#!/usr/bin/env python3
"""Evidence / SOC / Pentest Findings Summary DOCX renderer.

Usage: render.py <data.json> <out.docx>

Consumes the `evidence-summary` JSON contract emitted by the
tpa-evidence-analyzer, soc-report-analyzer and pentest-report-analyzer
agents (verified + human-approved before this runs):

{
  "title": str, "supplier": str, "service": str, "reportDate": "YYYY-MM-DD",
  "classification": str,                     # default "Euronext Internal"
  "executiveSummary": [str, ...],
  "verdict": str,                            # e.g. RELIANCE OK / CONDITIONS
  "identification": [{"field": str, "value": str}, ...],
  "inventory":  [{...}] | null,              # d2 per-file table (any keys)
  "findings":   [{"id","title","severity","source","detail","status"?}, ...],
  "cuecs":      [{...}] | null,              # SOC CUEC mapping (any keys)
  "timeline":   [{...}] | null,              # d2 validity timeline
  "actions":    [{"action","priority","owner","due"?}, ...]
}
"""

from __future__ import annotations

import json
import sys
from datetime import date

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

TEAL = RGBColor(0x00, 0x8D, 0x7F)          # house theme RGB(0,141,127)
SEV = {"CRITICAL": RGBColor(0xB0, 0x00, 0x20),
       "HIGH": RGBColor(0xD9, 0x53, 0x19),
       "MEDIUM": RGBColor(0xC9, 0x9A, 0x06),
       "LOW": RGBColor(0x2E, 0x7D, 0x32),
       "INFO": RGBColor(0x55, 0x55, 0x55)}


def h(doc, text, level=1):
    p = doc.add_heading(text, level=level)
    for r in p.runs:
        r.font.color.rgb = TEAL
    return p


def table(doc, rows: list[dict], columns: list[str] | None = None):
    if not rows:
        return
    columns = columns or list(rows[0].keys())
    t = doc.add_table(rows=1, cols=len(columns))
    t.style = "Light Grid Accent 1"
    for i, c in enumerate(columns):
        cell = t.rows[0].cells[i]
        cell.text = c.replace("_", " ").title()
        for r in cell.paragraphs[0].runs:
            r.font.bold = True
    for row in rows:
        cells = t.add_row().cells
        for i, c in enumerate(columns):
            cells[i].text = str(row.get(c, "") or "")
            sev = str(row.get(c, "")).upper()
            if c.lower() == "severity" and sev in SEV:
                for r in cells[i].paragraphs[0].runs:
                    r.font.color.rgb = SEV[sev]
                    r.font.bold = True


def main() -> int:
    data = json.loads(open(sys.argv[1], encoding="utf-8").read())
    doc = Document()
    for s in doc.styles["Normal"].font, :
        s.name, s.size = "Verdana", Pt(10)

    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = t.add_run(data["title"])
    r.font.size, r.font.bold, r.font.color.rgb = Pt(18), True, TEAL
    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.add_run(f"{data.get('supplier','')} — {data.get('service','')}  |  "
                f"{data.get('reportDate', date.today().isoformat())}  |  "
                f"{data.get('classification', 'Euronext Internal')}")

    h(doc, "Executive Summary")
    for b in data.get("executiveSummary", []):
        doc.add_paragraph(b, style="List Bullet")
    if data.get("verdict"):
        p = doc.add_paragraph()
        r = p.add_run(f"Verdict: {data['verdict']}")
        r.font.bold = True

    if data.get("identification"):
        h(doc, "Identification")
        table(doc, data["identification"], ["field", "value"])
    if data.get("inventory"):
        h(doc, "Evidence Inventory")
        table(doc, data["inventory"])
    if data.get("timeline"):
        h(doc, "Validity Timeline")
        table(doc, data["timeline"])
    if data.get("findings"):
        h(doc, "Findings Register")
        table(doc, data["findings"])
    if data.get("cuecs"):
        h(doc, "Complementary User-Entity Controls (CUECs)")
        table(doc, data["cuecs"])
    if data.get("actions"):
        h(doc, "Recommended Actions")
        table(doc, data["actions"])

    doc.add_paragraph()
    foot = doc.add_paragraph(
        "Generated by the InfoSec Assurance platform — verified and "
        "human-approved before storage. Sources cited per item in the "
        "originating analysis thread.")
    foot.runs[0].font.size = Pt(8)

    doc.save(sys.argv[2])
    return 0


if __name__ == "__main__":
    sys.exit(main())
